// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenisAhora.Infrastructure.Persistence;

#nullable disable

namespace TenisAhora.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipoInscripcion_competencia", b =>
                {
                    b.Property<int>("EquiposId")
                        .HasColumnType("int");

                    b.Property<int>("InscripcionesCompetenciaId")
                        .HasColumnType("int");

                    b.HasKey("EquiposId", "InscripcionesCompetenciaId");

                    b.HasIndex("InscripcionesCompetenciaId");

                    b.ToTable("EquipoInscripcion_competencia");
                });

            modelBuilder.Entity("EquipoSocio", b =>
                {
                    b.Property<int>("EquiposId")
                        .HasColumnType("int");

                    b.Property<int>("SociosId")
                        .HasColumnType("int");

                    b.HasKey("EquiposId", "SociosId");

                    b.HasIndex("SociosId");

                    b.ToTable("EquipoSocio");
                });

            modelBuilder.Entity("ReservaSocio", b =>
                {
                    b.Property<int>("ReservasId")
                        .HasColumnType("int");

                    b.Property<int>("SociosId")
                        .HasColumnType("int");

                    b.HasKey("ReservasId", "SociosId");

                    b.HasIndex("SociosId");

                    b.ToTable("ReservaSocio");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Actividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CantidadDeAlumnos")
                        .HasColumnType("int");

                    b.Property<int>("CapacidadMaxma")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int?>("EntrenadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrenadorId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Actividades");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<bool>("presente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ActividadId");

                    b.HasIndex("SocioId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Cancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TipoDeCanchaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TipoDeCanchaId");

                    b.ToTable("Canchas");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.CertificacionDeportiva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnteEmisor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCertificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("certificacionDeportiva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId")
                        .IsUnique();

                    b.ToTable("CertificacionesDeportivas");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Competencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReglamentoId")
                        .HasColumnType("int");

                    b.Property<int>("categoriaGenero")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<int>("modalidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReglamentoId");

                    b.ToTable("Competencias");

                    b.HasDiscriminator().HasValue("Competencia");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Descuento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("condiciones")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("porcentaje")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Descuentos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Detalle_stock_reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReservaId");

                    b.HasIndex("StockId");

                    b.ToTable("DetallesStockReserva");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Disponibilidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Disponibilidades");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SocioId")
                        .HasColumnType("int");

                    b.Property<int>("estadoInscripcion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SocioId");

                    b.ToTable("Inscripciones");

                    b.HasDiscriminator().HasValue("Inscripcion");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Pago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DescuentoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha_pago")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InscripcionId")
                        .HasColumnType("int");

                    b.Property<int?>("ReservaId")
                        .HasColumnType("int");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.Property<float>("porcentaje_pago")
                        .HasColumnType("real");

                    b.Property<int>("tipo_pago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DescuentoId");

                    b.HasIndex("InscripcionId");

                    b.HasIndex("ReservaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ronda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("CompetenciaId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodigoPostal")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaDeNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");

                    b.HasDiscriminator().HasValue("Persona");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Recibo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime2");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("PagoId")
                        .IsUnique();

                    b.ToTable("Recibos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reglamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoReglamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vigencia")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Reglamentos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reporte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<string>("contenido_detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo_reporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CanchaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("fecha_reserva")
                        .HasColumnType("datetime2");

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("cantidad_disponible")
                        .HasColumnType("int");

                    b.Property<string>("tipo_elemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.TipoDeCancha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("capacidad")
                        .HasColumnType("int");

                    b.Property<double>("precio")
                        .HasColumnType("float");

                    b.Property<int>("superficie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TiposDeCancha");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Liga", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Competencia");

                    b.Property<int>("Cantidad_fechas")
                        .HasColumnType("int");

                    b.Property<int>("puntos_por_partido")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Liga");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Torneo", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Competencia");

                    b.Property<string>("etapa_actual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tipo_llave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Torneo");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion_actividad", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Inscripcion");

                    b.Property<int>("ActividadId")
                        .HasColumnType("int");

                    b.HasIndex("ActividadId");

                    b.HasDiscriminator().HasValue("Inscripcion_actividad");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion_competencia", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Inscripcion");

                    b.Property<int>("CompetenciaId")
                        .HasColumnType("int");

                    b.HasIndex("CompetenciaId");

                    b.HasDiscriminator().HasValue("Inscripcion_competencia");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Administrador", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Persona");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Instructor", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Persona");

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<int>("antiguedad")
                        .HasColumnType("int");

                    b.Property<string>("especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("AdministradorId");

                    b.HasDiscriminator().HasValue("Instructor");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Socio", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Persona");

                    b.Property<int>("estadoMembresia")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Socio");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Entrenador", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Instructor");

                    b.HasDiscriminator().HasValue("Entrenador");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Profesor", b =>
                {
                    b.HasBaseType("TenisAhora.Domain.Entities.Instructor");

                    b.HasDiscriminator().HasValue("Profesor");
                });

            modelBuilder.Entity("EquipoInscripcion_competencia", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Inscripcion_competencia", null)
                        .WithMany()
                        .HasForeignKey("InscripcionesCompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EquipoSocio", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Equipo", null)
                        .WithMany()
                        .HasForeignKey("EquiposId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Socio", null)
                        .WithMany()
                        .HasForeignKey("SociosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReservaSocio", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Reserva", null)
                        .WithMany()
                        .HasForeignKey("ReservasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Socio", null)
                        .WithMany()
                        .HasForeignKey("SociosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Actividad", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Entrenador", "Entrenador")
                        .WithMany("Actividades")
                        .HasForeignKey("EntrenadorId");

                    b.HasOne("TenisAhora.Domain.Entities.Profesor", "Profesor")
                        .WithMany("Actividades")
                        .HasForeignKey("ProfesorId");

                    b.Navigation("Entrenador");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Actividad", "Actividad")
                        .WithMany("Asistencias")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Socio", "Socio")
                        .WithMany("Asistencias")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Cancha", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.TipoDeCancha", "TipoDeCancha")
                        .WithMany("Canchas")
                        .HasForeignKey("TipoDeCanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDeCancha");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.CertificacionDeportiva", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Instructor", "instructor")
                        .WithOne("certificacionDeportiva")
                        .HasForeignKey("TenisAhora.Domain.Entities.CertificacionDeportiva", "InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("instructor");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Competencia", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Reglamento", "Reglamento")
                        .WithMany("Competencias")
                        .HasForeignKey("ReglamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reglamento");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Descuento", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Administrador", "Administrador")
                        .WithMany("Descuentos")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Detalle_stock_reserva", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Reserva", "Reserva")
                        .WithMany("DetallesStockReserva")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Stock", "Stock")
                        .WithMany("DetallesStockReserva")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reserva");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Disponibilidad", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Disponibilidades")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Socio", "Socio")
                        .WithMany("Inscripciones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Pago", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Descuento", "Descuento")
                        .WithMany("Pagos")
                        .HasForeignKey("DescuentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenisAhora.Domain.Entities.Inscripcion", "Inscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("InscripcionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TenisAhora.Domain.Entities.Reserva", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Descuento");

                    b.Navigation("Inscripcion");

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Partido", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Partidos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TenisAhora.Domain.Entities.Competencia", "Competencia")
                        .WithMany("Partidos")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Recibo", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Pago", "Pago")
                        .WithOne("Recibo")
                        .HasForeignKey("TenisAhora.Domain.Entities.Recibo", "PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reporte", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Administrador", "Administrador")
                        .WithMany("Reportes")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Reservas")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion_actividad", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Actividad", "Actividad")
                        .WithMany("InscripcionesActividad")
                        .HasForeignKey("ActividadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actividad");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion_competencia", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Competencia", "Competencia")
                        .WithMany("Inscripciones")
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Competencia");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("TenisAhora.Domain.Entities.Administrador", "Administrador")
                        .WithMany("Instructores")
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Actividad", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("InscripcionesActividad");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Disponibilidades");

                    b.Navigation("Partidos");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Competencia", b =>
                {
                    b.Navigation("Inscripciones");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Descuento", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Inscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Pago", b =>
                {
                    b.Navigation("Recibo")
                        .IsRequired();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reglamento", b =>
                {
                    b.Navigation("Competencias");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Reserva", b =>
                {
                    b.Navigation("DetallesStockReserva");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Stock", b =>
                {
                    b.Navigation("DetallesStockReserva");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.TipoDeCancha", b =>
                {
                    b.Navigation("Canchas");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Administrador", b =>
                {
                    b.Navigation("Descuentos");

                    b.Navigation("Instructores");

                    b.Navigation("Reportes");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("certificacionDeportiva")
                        .IsRequired();
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Socio", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Inscripciones");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Entrenador", b =>
                {
                    b.Navigation("Actividades");
                });

            modelBuilder.Entity("TenisAhora.Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Actividades");
                });
#pragma warning restore 612, 618
        }
    }
}
